-- Creating table mess_menus
CREATE TABLE mess_menus (
    id SERIAL PRIMARY KEY,
    month INT NOT NULL,
    year INT NOT NULL,
    monday_breakfast JSON,
    monday_lunch JSON,
    monday_snacks JSON,
    monday_dinner JSON,
    tuesday_breakfast JSON,
    tuesday_lunch JSON,
    tuesday_snacks JSON,
    tuesday_dinner JSON,
    wednesday_breakfast JSON,
    wednesday_lunch JSON,
    wednesday_snacks JSON,
    wednesday_dinner JSON,
    thursday_breakfast JSON,
    thursday_lunch JSON,
    thursday_snacks JSON,
    thursday_dinner JSON,
    friday_breakfast JSON,
    friday_lunch JSON,
    friday_snacks JSON,
    friday_dinner JSON,
    saturday_breakfast JSON,
    saturday_lunch JSON,
    saturday_snacks JSON,
    saturday_dinner JSON,
    sunday_breakfast JSON,
    sunday_lunch JSON,
    sunday_snacks JSON,
    sunday_dinner JSON
);